using SQLite;
using System;
using System.Collections.Generic;
using System.Text;

namespace MuslceWizard
{
    public class Exercise
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }

        static public Array GetDefaultData()
        {
            string[,] exercises = new string[40, 5] {
                {"1","Bench Press","The barbell bench press is a classic exercise popular among all weight lifting circles. From bodybuilders to powerlifters, the bench press is a staple chest exercise in nearly every workout program. For powerlifters, it is known as one of the “big three” lifts which includes the squat, deadlift, and bench press. For athletes, 1 rep max on bench press is a good indicator for on field/court performance. And for bodybuilders, the bench press is a compound exercise that targets many of the muscles in your upper body. By performing the bench press, you primarily work your pectoralis major (your chest). Other muscles which assist in moving the barbell during a bench press are other muscles of the chest, triceps, and shoulders. Not everyone is built to perform the traditional barbell bench press, so several variations have been created to ensure people can train this crucial movement pattern in a safe and comfortable way.","https://www.muscleandstrength.com/exercises/barbell-bench-press.html","Chest"},
                {"2","Dumbbell Flyes","The dumbbell fly utilizes a chest fly movement pattern to isolate the muscles fo the chest to better help the muscles grow and become stronger. The dumbbell fly is often thought of as a classic bodybuilding movement as the goal of the exercise is to isolate the chest for aesthetic purposes. The movement itself can be used to help build a stronger bench press but isn’t typically thought of from an increased performance stand-point.Thus, this movement is best reserved for traditional chest workouts in bodybuilding style splits.","https://www.muscleandstrength.com/exercises/dumbbell-flys.html","Chest"},
                {"3","Incline Bench Press","The incline bench press is one of the hardest bench variations because the incline reduces your ability to optimally recruit your pec muscles as a whole and it instead disproportionately places stress on the upper pecs and shoulders, putting your upper body at a disadvantage.20 May 2021","https://www.muscleandstrength.com/exercises/incline-bench-press.html","Chest"},
                {"4","Push-ups","The push-up builds both upper-body and core strength.1 It has many modifications; beginners can start with easier versions, while more advanced exercisers can use a challenging variation. You can do the push-up as part of a bodyweight exercise session, a circuit training workout, or a strength workout.","https://www.verywellfit.com/the-push-up-exercise-3120574","Chest"},
                {"5","Cable Crossover","The bench press is not enough. Sure, big multi-joint lifts are very efficient at putting heaps of meat on your frame, but if you really want to take your muscular development to the next level, you’ll have to include some isolation (single-joint) movements to specifically target individual body parts.","https://breakingmuscle.com/cable-crossover/","Chest"},
                {"6","Barbell Bicep Curl","Biceps training may take a back seat to more popular strength moves like back squats, deadlifts, and overhead presses. It’s true that you want to prioritize those compound moves in your workout split, but you may want to let barbell curls ride shotgun. (Ok, that’s the last car pun.) ","https://barbend.com/barbell-curl/","Biceps"},
                {"7","Dumbbell Hammer Curl","A hammer curl is a variation of the biceps curl and targets muscles in the upper and lower arm. While this exercise is almost always performed with a dumbbell, you can also perform it with cables or bands. The hammer curl is a great addition to an upper-body strength routine. Stand with your legs straight (but not stiff or locked) and knees aligned under the hips. Your arms are at your side with a dumbbell in each hand, the weights resting next to the outer thigh. Your palms are facing the thighs, the thumbs are facing forward, and your shoulders are relaxed.","https://www.verywellfit.com/how-to-hammer-curls-techniques-benefits-variations-4788329","Biceps"},
                {"8","Preacher Curl","Bicep curls are an exercise that almost every lifter does. Newbies to advanced lifters all know how to work those biceps. There's arguably no more satisfying muscle to train. Who doesn't like seeing their biceps swell after each rep while watching themselves in the mirror? When it comes to this, it isn't narcassim, it's simply bodybuilding. Now, one of the most solid variations in the biceps realm, which is often neglected, is the preacher curl. The exercise is simple, you sit down with your upper arms positioned on the preacher curl bench and then curl. It can be done with dumbbells, an EZ bar, or even a barbell. It's a great way to better isolate your biceps and forearms than other curl variations because you can't use any 'body English', or in other words, you can't cheat.","https://www.setforset.com/blogs/news/preacher-curl","Biceps"},
                {"9","Concentration Curl","The concentration curl is a bodybuilding favorite for building biceps. Some promote the concentration curl claiming it to be an exercise guaranteed to produce a bicep pump and build the mind muscle connection.  With that said, the slow tempo typically used during the concentration curl is great for building the biceps and since it is an unilateral exercise, it helps work each bicep equally.","https://www.muscleandstrength.com/exercises/concentration-cur.html","Biceps"},
                {"10","Cable Curl","The biceps cable curl is an isolation exercise for the biceps muscles in the upper arm. The pulling action is performed with a cable machine and is suitable for beginners. This exercise can be used as part of an upper-body muscle-building program.","https://www.verywellfit.com/how-to-do-the-biceps-cable-curl-3498289","Biceps"},
                {"11","Crunches","The crunch is a classic core exercise. It specifically trains your abdominal muscles, which are part of your core. Your core consists not only of your abs. It also includes your oblique muscles on the sides of your trunk, as well as the muscles in your pelvis, lower back, and hips. Together, these muscles help stabilize your body. While the crunch is a popular core move, it isn’t safe for everyone. It can place a lot of stress on your back and neck, and it only works your abs, not the other muscles in your core. In this article, we’ll look at the pros and cons of doing crunches, and how to do the exercise with good form. We’ll also explore alternative exercises that may be safer and more effective at working your core muscles.","https://www.healthline.com/health/exercise-fitness/how-to-do-crunches","Abs"},
                {"12","Plank","If there’s one exercise we all love to hate and hate to love, it’s this one. A plank is a simple, effective bodyweight exercise that requires no equipment and can be performed just about anywhere (well, use your judgment). Holding your body (light as a feather) stiff as a board develops strength primarily in your core — the muscles that connect your upper body and lower body — as well as your shoulders, arms, and glutes. Find out how to perfect your planking (no, not that kind) and fix some of the most common plank mistakes with this guide.","https://greatist.com/fitness/perfect-plank","Abs"},
                {"13","Bicycle Crunches","The bicycle crunch is excellent for activating the rectus abdominis, your upper abdominal muscle, and it is second only to the captain's chair for activating the obliques—your side abdominal muscles. Because you are raising your legs, you also engage the transverse abdominis, which is the deep ab muscle that is hard to target. Besides working your abs, you will also be toning your thighs as both your hamstrings and quads will be involved with bicycling. A strong core will help you with maintaining good posture and performing well at your daily tasks. It is also a key component of good performance in sports and physical activities. Doing a variety of ab and core exercises ensures you are engaging your muscles in different ways.","https://www.verywellfit.com/bicycle-crunch-exercise-3120058","Abs"},
                {"14","Russian Twist","The Russian twist is a great exercise to build core and shoulder strength. Athletes use it for rotational movement, which can be seen in sports. Though it seems easy, it takes a lot of effort and stability.","https://www.healthline.com/health/russian-twist","Abs"},
                {"15","Leg Raises","Are you looking for a core-boosting exercise you can do in a matter of minutes with zero equipment? Leg lifts hold the power to help build a strong trunk as a part of your abs routine. That can mean improved posture, less back pain and more strength to power your workouts. “When you think of an exercise routine for your core, most people think of sit-ups or planks, which are great exercises for your ‘six-pack’ ab work,” says exercise physiologist Griffin Nykor, RKin, CPT. “Leg lifts are an important complement to that because they get at the muscles that make up the rest of your trunk — your lower back, glutes, hip flexors and your transverse abdominus (the muscle that sits under your six-pack).” Nykor breaks down how to do traditional leg lifts, as well as some variations on this workout heavy-hitter.  ","https://health.clevelandclinic.org/how-to-do-leg-lifts/","Abs"},
                {"16","Barbell Squats","There are a number of exercises out there that can help you build a strong core. But if you're looking for a little extra challenge and a way to change up your usual floor routine, consider adding hanging leg raises to the mix. This move will not only challenge your lower abs but also put your entire body to the test (think shoulders, back, and more). Before adding it to your fitness repertoire, however, it's important to understand the correct form—doing so will help you train your muscles properly and efficiently.","https://www.mindbodygreen.com/articles/hanging-leg-raises","Quads"},
                {"17","Lunges","The lunge is a multi-joint exercise that can help tone and strengthen many muscles in the lower body. This includes the quads (front of the thighs), hamstrings (back of the thighs), glutes (buttocks), and calves (back of the lower leg). Your hip flexors are stretched during the lunge. This improves their flexibility and counteracts the shortening and tightening that can happen when you sit for long periods.1 You also engage your core muscles for stability, which can help you maintain balance2 and prevent injuries.Another benefit of lunges is that they are a functional exercise. This means that they mimic actions you take throughout daily life, such as when picking something up from the floor. Since lunges work large lower-body muscle groups, it may even improve your metabolism.4 When compared to other lower-body exercises such as squats, the split stance used in lunges changes the load on your body, allowing you to work each leg more independently.","https://www.verywellfit.com/how-to-lunge-variations-modifications-and-mistakes-1231320","Quads"},
                {"18","Leg Press","The leg press is a popular piece of gym equipment that can help build key muscles in your legs. There are two leg press machines commonly found in gyms and home gyms: the standard horizontal leg press and the 45-degree leg press, with a seat that reclines at an angle while your legs press upward in a diagonal direction. Both machines develop the quadriceps and hamstrings of the thigh and the gluteus (buttocks). While it seems like a simple exercise, it's essential to learn how to use it properly. Paying attention to your form can maximize the strength-building benefits and prevent injury. The leg press is used as part of a leg strengthening routine or a machine circuit workout. We've researched and reviewed the best home gyms. If you're in the market for a home gym, explore which option may be best for you.","https://www.verywellfit.com/how-to-do-the-leg-press-3498610","Quads"},
                {"19","Leg Extensions","Leg extensions are exercises usually done with a lever machine. You sit on a padded seat and raise a padded bar with your legs. The exercise works mainly the quadriceps muscles of the front of the thigh—the rectus femoris and the vastus muscles. You can use this exercise to build lower body strength and muscle definition as part of a strength training workout.","https://www.verywellfit.com/leg-extensions-benefit-or-risk-3498573","Quads"},
                {"20","Step-Ups","A step-up is one of my favorite moves for multiple reasons, says NASM-certified trainer Justin Norris, cofounder of the LIT Method. 'First, I am a big fan of stability and strength, and that's exactly what this move focuses on. During a step-up, you are activating your hamstrings, glutes, core, and stabilizers.' All those muscles work synergistically to execute the movement, says Eric O'Connor, certified CrossFit coach, which can even increase your functional range of motion (i.e. mobility) when performed correctly. Not to mention, it's a great way to build unilateral — aka single-leg — strength. 'The unilateral nature of the step-up is a nice complement to the bilateral elements [think: traditional squats, deadlifts, etc.] commonly performed in the gym,' he says. 'Not only is strength being developed but there are additional stability, coordination, and balance demands required of this movement.' That's right: aside from a lower-body burn, step-ups are also a great cardio and core exercise. They get your heart rate up and also require balance, forcing you to engage your core for stability.","https://www.popsugar.com/fitness/How-Do-Step-Ups-6483533","Quads"},
                {"21","Barbell Shrugs","The shrug is the universal movement for when we want to indicate that we don’t know something. However, it’s also the universal lift for getting massive and strong traps. The barbell shrug is a simple lift that’ll make your upper back bigger, stronger, and more resilient to injury. And a stronger upper back goes far in helping with your other lifts. Giving this muscle group its deserved attention should be a no-brainer, and here’s the best way to go about it: Just shrugging weight is a terrific way to develop your traps especially, and give you a healthier upper back overall. The barbell is particularly useful for this because you can load up a ton of weight onto your traps. Since both sides of your body are working together to move the same load, you’re going to be able to move a lot more. And as we all know, the more weight we move, the more gains we experience. The barbell shrug hits all the markers for a necessary lift if you’re looking to develop your upper back.","https://steelsupplements.com/blogs/steel-blog/how-to-do-barbell-shrugs-form-benefits","Trepezius"},
                {"22","Dumbbell Shrugs","The dumbbell shrug is a variation of the shrug and an exercise used to build trap muscle size. Traps, being a stubborn muscle group for many, can be trained with a fairly high frequency during the week. When doing so, be sure to mix up the volume, intensity, and implements you use to train the traps. Dumbbell shrugs can be included into your shoulder workouts, back workouts, upper body workouts, and full body workouts.","https://www.muscleandstrength.com/exercises/dumbbell-shrugs.html","Trepezius"},
                {"23","Upright Rows","The barbell upright row is one of the best exercises for building the upper traps and shoulders. Load up a barbell with the weight you want to use and stand facing it with your feet at around shoulder width apart.Grasp the barbell with an overhand grip (palms facing down), and hands slightly closer than shoulder width apart.Pick the bar up, bending at the knees and keeping your back straight.Keeping your back straight and eyes facing forwards, lift the bar straight up while keeping it as close to your body as possible (you should pull the bar up to around chest height - nearly touching your chin). Pause, and then slowly lower the bar back to the starting position. Repeat for desired reps.","https://www.muscleandstrength.com/exercises/upright-row.html","Trepezius"},
                {"24","Face Pulls","Face pulls use a cable machine with a rope attachment to train the rear deltoids, the muscles in the back of the shoulders, with support from the traps, rhomboids and rotator cuff. Strengthening these muscles can help with poor posture, improve shoulder stability, and help with overall shoulder and back strength. The most popular of shoulder movements typically include pressing and raise movements which mostly work the anterior and lateral delts and neglect the rear delts. Including rear delt exercises like the face pull is important for building strong, healthy shoulders. It also helps to prevent muscular imbalances between the front and back of your body, which can lead to poor posture like slumping.","https://www.puregym.com/exercises/arms-and-shoulders/rear-delt-exercises/face-pulls/#:~:text=Face%20pulls%20use%20a%20cable,overall%20shoulder%20and%20back%20strength.","Trepezius"},
                {"25","Power Cleans","The power clean is an explosive whole body movement used by weightlifters and athletes to develop strength and power. While it began as an essential Olympic weightlifting movement, the power clean has become a staple in the training programs of team athletes and people who practice CrossFit. This movement is broken down into several phases and requires a good deal of technique to perform properly. In this article, we’ll review the power clean, including how to perform it, a few variations, its benefits, the muscles worked, and several common mistakes people make when doing this exercise.","https://www.healthline.com/health/fitness/power-clean","Trepezius"},
                {"26","Close-Grip Bench Press","The close grip bench press differs from the traditional bench press in that you perform the press with a narrower grip. This position places emphasis on building strength and size in the triceps muscles, as well as the chest. Performing a close grip press is a great way to add variety to upper body and pushing muscle workouts. Athletes using close push actions as in football, basketball, or rugby especially benefit from this type of sports-specific exercise, according to research. Pressing with a narrow grip is also beneficial for lifters with shoulder injuries unable to perform a traditional bench press. When the grip width is reduced it creates less shoulder abduction said to limit the stress placed on the shoulder joint. You may be new to weight lifting or seasoned lifter wanting to improve an upper body routine. Adding the close grip bench press to your program is a great way to build strength and is easily modified to every fitness level.","https://www.verywellfit.com/close-grip-bench-press-4686827","Triceps"},
                {"27","Tricep Dips","The triceps dip is one of the most effective exercises for activating the triceps brachii muscle in the back of your upper arm.1 Additionally, you must activate your core as you hold your hips off the ground. We use our triceps to extend our elbows. They're also used for pushing, so you engage them in any daily activities that require a pushing motion. This includes pushing a lawnmower or a shopping cart and other similar movements. It's also important to keep your body in balance. So, if you participate in sports that use a lot of pulling actions (which involve the biceps), you need to maintain strength in your triceps to prevent muscle imbalances and injury.","https://www.verywellfit.com/the-chair-dip-triceps-exercise-3120734","Triceps"},
                {"28","Overhead Tricep Extension","The triceps brachii is a three-headed muscle that’s involved in two primary actions.The first is extending, or straightening, the elbow. The second is helping pull the arm down from an overhead or front-of-body position. Additionally, the triceps are important stabilizers in the shoulder joints. The muscle originates at the back of the scapula and on the back of the upper arm bone, which is known as the humerus. It runs the length of the back of the upper arm to attach to the tip of the elbow, which is called the olecranon process of the ulna =. There are 3 heads to the triceps: the medial, lateral, and long heads. During overhead tricep presses, the long head tends to be most active during the entire movement. Still, overhead tricep extensions are an excellent way to target all three heads, and a great exercise to add to your fitness routine.","https://www.healthline.com/health/fitness/overhead-triceps-extension#:~:text=Slowly%20bend%20your%20elbows%20and,extend%20the%20weight%20back%20overhead.","Triceps"},
                {"29","Cable Tricep Pushdowns","As you prepare for this move, face the tricep pushdown cable machine and grasp the horizontal cable bar or rope attachment (depending on the machine your gym has) with an overhand grip.1 Adjust the bar or rope grips to about chest level. Use the pin-and-place adjustment and set a low weight to start. Different versions of the machine may include other weighting mechanisms.","https://www.verywellfit.com/how-to-do-the-triceps-pushdown-3498613","Triceps"},
                {"30","Skull Crushers","Lie face up on a flat gym bench. Your entire body should be on the bench, except your lower legs. Your knees are bent, and your feet are flat on the floor. Arms extend above the chest, elbows shoulder-width apart (not locked), and both hands hold one end of a dumbbell. Flex your elbows and lower the weight toward the top of your head. Your upper arms should remain relatively perpendicular to your body. This keeps the tension on the triceps versus shifting it to the shoulders. Continue lowering the weight behind the head. The bottom of the dumbbell head should be about in line with the bench's top, or even a little higher if this feels unwieldy. Reverse the movement until the weight is above the chest in the original starting position. Keep from locking the elbow to maintain tension in your triceps muscle. Repeat. You can do skull crushers while holding one dumbbell with both hands or, if you want to use more weight, you can hold two dumbbells, one in each hand.","https://www.verywellfit.com/doing-the-triceps-extension-skullcrusher-3498313","Triceps"},
                {"31","Barbell or Dumbbell Lunges","Both Barbell Lunges and Dumbbell Lunges are popular lower body movements that can help to strengthen the legs and glutes, but they differ in the type of equipment used. The question is, is one of these lunge variations better than the other? In this article, we will take a closer look at the benefits and drawbacks of each exercise, as well as provide tips on how to properly execute the movements to get the most out of your workouts. Whether you are a beginner or a seasoned gym-goer, this comparison will provide valuable insights to help you decide which lunge variation is right for you.","https://hortonbarbell.com/barbell-lunge-vs-dumbbell-lunge/#:~:text=Barbell%20Lunges%2C%20because%20of%20the,for%20building%20size%20and%20strength.","Glutes"},
                {"32","Squats","You’re practicing squats every day, almost effortlessly, without even noticing. Every time you sit down and stand up, you’re performing a squat, making this functional exercise one you should know how to do properly. Plus, adding squats and squat variations to your strength training routine can aid your performance and protect your muscles. While practicing squats will benefit your joint and muscle health, as well as your posture, they also help to improve your running form and speed, explains Noam Tamir, C.S.C.S., CEO and founder of TS Fitness in New York City.","https://www.runnersworld.com/training/a32256640/how-to-do-a-squat/","Glutes"},
                {"33","Deadlifts","The deadlift is a great way to build strong legs and butt. In a deadlift, you lift the weight from the ground to thigh-level using primarily your leg and hip muscles, but with the assistance of most of the large muscle groups of your body. The deadlift is usually performed with a bar and plates or a fixed barbell, but you can also do it with dumbbells. It is a specialty of powerlifters that you shouldn't ignore in general fitness weight training. Make the deadlift part of your strength training workouts to build muscle and functional fitness.","https://www.verywellfit.com/how-to-do-the-deadlift-3498608","Glutes"},
                {"34","Hip Thrusts","Few exercises compare to the hip thrust when you’re on the mission of building strong and powerful glutes. In the fitness world, the hip thrust has grown in popularity due to the increased understanding of how strong glutes carry over to pretty much every aspect of life, especially performance in sport and the gym. This article breaks down how to properly perform hip thrusts, their benefits, muscles worked, variations, and mistakes to avoid. ","https://barbend.com/hip-thrusts/","Glutes"},
                {"35","Step-ups","Want to work your legs and butt but don't have any weights? Find a step, box, bench, or sturdy chair and learn how to do a step-up. This exercise combines the movement of a lunge with stepping upward, like climbing stairs, to build functional strength. 'A step-up is one of my favorite moves for multiple reasons,' says NASM-certified trainer Justin Norris, cofounder of the LIT Method. 'First, I am a big fan of stability and strength, and that's exactly what this move focuses on. During a step-up, you are activating your hamstrings, glutes, core, and stabilizers.' All those muscles work synergistically to execute the movement, says Eric O'Connor, certified CrossFit coach, which can even increase your functional range of motion (i.e. mobility) when performed correctly. Not to mention, it's a great way to build unilateral — aka single-leg — strength.","https://www.popsugar.com/fitness/How-Do-Step-Ups-6483533","Glutes"},
                {"36","Deadlifts","The deadlift is a great way to build strong legs and butt. In a deadlift, you lift the weight from the ground to thigh-level using primarily your leg and hip muscles, but with the assistance of most of the large muscle groups of your body. The deadlift is usually performed with a bar and plates or a fixed barbell, but you can also do it with dumbbells. It is a specialty of powerlifters that you shouldn't ignore in general fitness weight training. Make the deadlift part of your strength training workouts to build muscle and functional fitness.","https://www.verywellfit.com/how-to-do-the-deadlift-3498608","Hamstrings"},
                {"37","Leg Curls","Lying leg curls (also known in the short form, leg curls) is an isolation exercise that targets the back of the leg: the hamstrings and calf muscles. It can be performed in a variety of positions and makes an excellent addition to most any lower body strength training workout.","https://www.verywellfit.com/how-to-properly-execute-the-leg-curl-exercise-3498304#:~:text=To%20do%20standing%20leg%20curls,repeat%20on%20the%20other%20side.","Hamstrings"},
                {"38","Romanian Deadlifts","The Romanian deadlift (RDL) should be a staple in (almost) everyone’s training program. Whether your goals align with physique development, enhancement of athletic performance, or general health, the RDL is a tool worth having in your arsenal. Furthermore, the RDL can be customized to suit your needs, no matter your current skill level. You can perform this exercise working with limited equipment in your garage, or with heavy weights in a fully-furnished training facility.","https://barbend.com/romanian-deadlift/","Hamstrings"},
                {"39","Glute-Ham Raises","The glute-ham raise trains the hamstrings‘ two key functions simultaneously. Sets of 5–8 reps may be appropriate to start; later, the glute-ham raise can be trained with low-, moderate-, and high-rep ranges. The glute-ham raise movement can be approximated with the Nordic hamstring curl, and other variations that don’t require a glute-ham bench.","https://www.onnit.com/academy/glute-ham-raises/","Hamstrings"},
                {"40","Good Mornings","The good morning exercise works the hamstrings, back, glutes, and abs. Using a weighted barbell increases the load on these muscles,1 though beginners should start with a light weight (or no weight at all). Add the barbell good morning to your lower body and core strength training routine.","https://www.verywellfit.com/how-to-do-the-good-morning-exercise-with-barbell-3498255","Hamstrings"},
            };
            return exercises;
        }
    }
}
